routes/web.php
<?php

Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('login', 'Auth\LoginController@login');
Route::post('logout', 'Auth\LoginController@logout')->name('logout');

Route::get('/', 'HomeController@index')->name('home');
Route::get('category/{slug}', 'HomeController@category')->name('category');
Route::post('order', 'HomeController@order')->name('order');
Route::post('accountingStore', 'HomeController@accountingStore')->name('accountingStore');
Route::view('/accountingIndex', 'accountingIndex');

Route::group(['prefix' => 'backend', 'middleware' => ['role:admin']], function () {

    Route::get('/', 'Admin\BackendController@index');
    Route::resource('accounting', 'Admin\AccountingController');
    Route::post('accountingByDay', 'Admin\AccountingController@accountingByDay')->name('accountingByDay');
    Route::resource('users', 'Admin\UserController');
    Route::resource('categories', 'Admin\CategoryController');
    Route::resource('products', 'Admin\ProductController');
    Route::post('updateOrder', 'Admin\ProductController@updateOrder')->name('updateOrder');
    Route::post('updateQuantity', 'Admin\ProductController@updateQuantity');
    //Orders page
    Route::post('ordersList', 'Admin\OrderController@index')->name('ordersList');
    Route::get('ordersView', 'Admin\OrderController@ordersView')->name('ordersView');
    Route::post('ordersAllList', 'Admin\OrderController@ordersAllList')->name('ordersAllList');
    Route::get('ordersAllView', 'Admin\OrderController@ordersAllView')->name('ordersAllView');

    Route::get('ordersReportView', 'Admin\OrderController@ordersReportView')->name('ordersReportView');
    Route::post('ordersReport', 'Admin\OrderController@ordersReport')->name('ordersReport');

    Route::get('system', 'Admin\SystemController@index')->name('system');
    Route::patch('systemUpdate/{id}', 'Admin\SystemController@update')->name('system.update');

    Route::get('/locationStore','Admin\LocationsController@store');
    Route::get('/locationUpdate','Admin\LocationsController@update');
    Route::get('/locationList','Admin\LocationsController@list');
    Route::view('/locationAdd', 'admin.location.store');
});

resources/views/admin/layouts/app.blade.php
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>@yield('title')</title>

    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <link rel="stylesheet" href="{{ asset('admin/') }}">
    <link rel="stylesheet" href="{{ asset('admin/bootstrap/dist/css/bootstrap.min.css') }}">
    <link rel="stylesheet" href="{{ asset('admin/font-awesome/css/font-awesome.min.css') }}">
    <link rel="stylesheet" href="{{ asset('admin/css/AdminLTE.min.css') }}">
    <link rel="stylesheet" href="{{ asset('admin/css/skin-blue.min.css') }}">
    <link rel="stylesheet" href="{{ asset('admin/morris.js/morris.css') }}">
    <link rel="stylesheet" href="{{ asset('admin/bootstrap-wysihtml5/bootstrap3-wysihtml5.min.css') }}">
@yield('css')
<!-- Google Font -->
    <link rel="stylesheet" href="{{ asset('admin/fonts/font.css') }}">
</head>

<body class="hold-transition skin-blue sidebar-mini">
<div class="wrapper">

    <header class="main-header">
        <!-- Logo -->
        <a href="{{ url('/') }}" class="logo">
            <!-- mini logo for sidebar mini 50x50 pixels -->
            <span class="logo-mini"><b>M</b>D</span>
            <!-- logo for regular state and mobile devices -->
            <span class="logo-lg"><b>Molochniy </b>Domik</span>
        </a>

        <nav class="navbar navbar-static-top">
            <!-- Sidebar toggle button-->
            <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
                <span class="sr-only">Toggle navigation</span>
            </a>
        </nav>
    </header>

    @include('admin.layouts.sidebar')

    <div class="content-wrapper">
        @if (session()->has('success'))
            <div class="alert alert-success alert-dismissible">
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                <h4><i class="icon fa fa-check"></i> Success!</h4>
                {{ session('success') }}
            </div>
        @endif
    @yield('content')

    </div>
</div>

<script src="{{ asset('admin/jquery/dist/jquery.min.js') }}"></script>
<script src="{{ asset('admin/jquery-ui/jquery-ui.min.js') }}"></script>
<!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
<script>
    $.widget.bridge('uibutton', $.ui.button);
</script>
<script src="{{ asset('admin/bootstrap/dist/js/bootstrap.min.js') }}"></script>
<script src="{{ asset('admin/jquery-sparkline/dist/jquery.sparkline.min.js') }}"></script>
<script src="{{ asset('admin/bootstrap-wysihtml5/bootstrap3-wysihtml5.all.min.js') }}"></script>
<script src="{{ asset('admin/jquery-slimscroll/jquery.slimscroll.min.js') }}"></script>
<script src="{{ asset('admin/fastclick/lib/fastclick.js') }}"></script>
<!-- AdminLTE App -->
<script src="{{ asset('admin/js/adminlte.min.js') }}"></script>
@yield('script')
</body>
</html>

resources/views/admin/layouts/sidebar.blade.php
<aside class="main-sidebar">
    <section class="sidebar">
        <ul class="sidebar-menu" data-widget="tree">
            <li class="header"> </li>
            <li>
                <a href="{{ route('users.index') }}">
                    <i class="fa fa-user"></i>
                    <span>Пользователи</span>
                </a>
            </li>
            <li class="treeview">
                <a href="#">
                    <i class="fa fa-map-marker"></i>
                    <span>Локация</span>
                    </span>
                </a>
                <ul class="treeview-menu">
                    <li><a href="{{ url('backend/locationAdd') }}"><i class="fa fa-circle-o"></i> Добавить</a></li>
                    <li><a href="{{ url('backend/locationList') }}"><i class="fa fa-circle-o"></i> Все</a></li>
                </ul>
            </li>
            <li>
                <a href="{{ route('categories.index') }}">
                    <i class="fa fa-share"></i>
                    <span>Категории</span>
                </a>
            </li>
            <li>
                <a href="{{ route('products.index') }}">
                    <i class="fa fa-apple"></i>
                    <span>Продукты </span>
                </a>
            </li>
            <li class="treeview">
                <a href="#">
                    <i class="fa fa-dollar"></i>
                    <span>Заказы</span>
            </span>
                </a>
                <ul class="treeview-menu">
                    <li><a href="{{ route('ordersView') }}"><i class="fa fa-circle-o"></i> Заказы по пользователям</a></li>
                    <li><a href="{{ route('ordersAllView') }}"><i class="fa fa-circle-o"></i> Заказы за весь день</a></li>
                </ul>
            </li>
            <li>
                <a href="{{ route('ordersReportView') }}">
                    <i class="fa fa-line-chart"></i>
                    <span>Аналитика</span>
                </a>
            </li>
            <li>
                <a href="{{ route('accounting.edit', ['id' => 1]) }}">
                    <i class="fa fa-calculator"></i>
                    <span>Бухгалтерия </span>
                </a>
            </li>
            {{--<li class="treeview">--}}
                {{--<a href="#">--}}
                    {{--<i class="fa fa-calculator"></i>--}}
                    {{--<span>Бухгалтерия</span>--}}
                    {{--</span>--}}
                {{--</a>--}}
                {{--<ul class="treeview-menu">--}}
                    {{--<li><a href="{{ route('accounting.index') }}"><i class="fa fa-circle-o"></i> Бухгалтерия по пользователям</a></li>--}}
                    {{--<li><a href="{{ route('accounting.edit', ['id' => 1]) }}"><i class="fa fa-circle-o"></i> Бухгалтерия за весь день</a></li>--}}
                {{--</ul>--}}
            {{--</li>--}}
            <li>
                <a href="{{ route('system') }}">
                    <i class="fa fa-line-chart"></i>
                    <span>Системные параметры</span>
                </a>
            </li>
            <li>
                <a href="{{ route('logout') }}" onclick="event.preventDefault();document.getElementById('logout-form').submit();">
                    <i class="fa fa-sign-out"></i>
                    <span>Выход</span>
                </a>
                <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                    @csrf
                </form>
            </li>
        </ul>
    </section>
</aside>