routes/web.php
<?php

Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('login', 'Auth\LoginController@login');
Route::post('logout', 'Auth\LoginController@logout')->name('logout');

Route::get('/', 'HomeController@index')->name('home');
Route::get('category/{slug}', 'HomeController@category')->name('category');
Route::post('order', 'HomeController@order')->name('order');
Route::post('accountingStore', 'HomeController@accountingStore')->name('accountingStore');
Route::view('/accountingIndex', 'accountingIndex');

Route::group(['prefix' => 'backend', 'middleware' => ['role:admin']], function () {

    Route::get('/', 'Admin\BackendController@index');
    Route::resource('accounting', 'Admin\AccountingController');
    Route::post('accountingByDay', 'Admin\AccountingController@accountingByDay')->name('accountingByDay');
    Route::resource('users', 'Admin\UserController');
    Route::resource('categories', 'Admin\CategoryController');
    Route::resource('products', 'Admin\ProductController');
    Route::post('updateOrder', 'Admin\ProductController@updateOrder')->name('updateOrder');
    Route::post('updateQuantity', 'Admin\ProductController@updateQuantity');
    //Orders page
    Route::post('ordersList', 'Admin\OrderController@index')->name('ordersList');
    Route::get('ordersView', 'Admin\OrderController@ordersView')->name('ordersView');
    Route::post('ordersAllList', 'Admin\OrderController@ordersAllList')->name('ordersAllList');
    Route::get('ordersAllView', 'Admin\OrderController@ordersAllView')->name('ordersAllView');

    Route::get('ordersReportView', 'Admin\OrderController@ordersReportView')->name('ordersReportView');
    Route::post('ordersReport', 'Admin\OrderController@ordersReport')->name('ordersReport');

    Route::get('system', 'Admin\SystemController@index')->name('system');
    Route::patch('systemUpdate/{id}', 'Admin\SystemController@update')->name('system.update');

    Route::get('/locationStore','Admin\LocationsController@store');
    Route::get('/locationUpdate','Admin\LocationsController@update');
    Route::get('/locationList','Admin\LocationsController@list');
    Route::view('/locationAdd', 'admin.location.store');
});

app/Http/Controllers/Admin/ProductController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Model\Category;
use App\Model\Product;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class ProductController extends Controller
{
    public function index()
    {
        $products = Product::orderBy('order')->get();
        return view('admin.product.index', compact('products'));
    }

    public function create()
    {
        $categories = Category::get();
        $categoriesArray = [];
        foreach ($categories as $item) {
            $categoriesArray[$item->id] = $item->name;
        }
        return view('admin.product.create', compact('categoriesArray'));
    }

    public function store(Request $request)
    {
        $this->validate($request, Product::$rules);

        //get highest order in product table
        $lastOrder = 1;
        $lastProductOrder = Product::orderBy('order', 'DESC')->take(1)->first();
        if (!empty($lastProductOrder))
            $lastOrder = $lastProductOrder->order + 1;

        $product = new Product();
        $product->title = $request->input('title');
        $product->category_id = $request->input('category_id');
        $product->price = $request->input('price');
        $product->quantity = 0;
        $product->order = $lastOrder;
        $product->save();

        return redirect()->route('products.index')->with('success', 'Product created successfully');
    }

    public function show($id)
    {
        return redirect()->route('products.index');
    }

    public function edit($id)
    {
        $product = Product::find($id);

        $categories = Category::get();
        $categoriesArray = [];
        foreach ($categories as $item) {
            $categoriesArray[$item->id] = $item->name;
        }

        return view('admin.product.edit', compact('product', 'categoriesArray'));
    }

    public function updateQuantity(Request $request)
    {
        $product = Product::find($request->id);
        $product->quantity = (int)filter_var($request->quantity, FILTER_SANITIZE_NUMBER_INT);
        $product->save();
        echo "";
    }

    public function updateOrder(Request $request)
    {
        $max = Product::max('order');
        $min = Product::min('order');

        if ($request['oldOrder'] == $min) {
            DB::table('product')
                ->where('order', '<=', $request['newOrder'])
                ->decrement('order');
        } else if ($request['oldOrder'] == $max) {
            DB::table('product')
                ->where('order', '>=', $request['newOrder'])
                ->increment('order');
        } else if ($request['newOrder'] > $request['oldOrder']) {
            DB::table('product')
                ->where('order', '>', $request['oldOrder'])
                ->where('order', '<=', $request['newOrder'])
                ->decrement('order');
        } else if ($request['newOrder'] < $request['oldOrder']) {
            DB::table('product')
                ->where('order', '>=', $request['newOrder'])
                ->where('order', '<', $request['oldOrder'])
                ->increment('order');
        }
        Product::where('id', $request['productId'])
            ->update(['order' => $request['newOrder']]);
        return redirect()->route('products.index')->with('success', 'Product updated successfully');
    }

    public function update(Request $request, $id)
    {
        $this->validate($request, Product::$rules);

        //Find the category and update its details
        $product = Product::find($id);
        $product->title = $request->input('title');
        $product->category_id = $request->input('category_id');
        $product->price = $request->input('price');
        $product->save();
        return redirect()->route('products.index')->with('success', 'Product updated successfully');
    }

    public function destroy($id)
    {
        Product::destroy($id);

        return redirect()->route('products.index')->with('success', 'Product deleted successfully');
    }
}

resources/views/admin/product/create.blade.php
<?php ?>
@extends('admin.layouts.app')
@section('title')
    Создать продукт
@endsection
@section('content')
    <section class="content">
        <div class="row">
            <!-- left column -->
            <div class="col-md-12">
                <!-- general form elements -->
                <div class="box box-primary">
                    <div class="box-header with-border">
                        <h3 class="box-title">Создать продукт</h3>
                    </div>

                    {!! Form::open(['route' => 'products.store']) !!}

                    @include('admin.product.fields')

                    {!! Form::close() !!}

                </div>
            </div>
        </div>
    </section>
@endsection

resources/views/admin/product/edit.blade.php
@extends('admin.layouts.app')
@section('title')
    Редактировать продукт
@endsection
@section('content')
    <section class="content">
        <div class="row">
            <!-- left column -->
            <div class="col-md-12">
                <!-- general form elements -->
                <div class="box box-primary">
                    <div class="box-header with-border">
                        <h3 class="box-title">Редактировать продукт</h3>
                    </div>

                    {!! Form::model($product, ['route' => ['products.update', $product->id], 'method' => 'patch']) !!}

                    @include('admin.product.fields')

                    {!! Form::close() !!}

                </div>
            </div>
        </div>
    </section>
@endsection

resources/views/admin/product/fields.blade.php
@if (count($errors) > 0)
    <div class="alert alert-danger alert-dismissible">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        <h4><i class="icon fa fa-ban"></i> Alert!</h4>
        @foreach ($errors->all() as $error)
            <p>{{ $error }}</p>
        @endforeach
    </div>
@endif

<div class="box-body">
    <div class="form-group {{ $errors->has('title') ? ' has-error' : '' }}">
        <label for="exampleInputEmail1">Название:</label>
        {{ Form::text('title', isset($product) ? $product->title : null, ['class' => 'form-control', 'required' => true]) }}
    </div>
    <div class="form-group {{ $errors->has('category_id') ? ' has-error' : '' }}">
        <label for="exampleInputEmail1">Категория:</label>
        {!! Form::select('category_id', ['' => 'Select'] + $categoriesArray, null, ['class' => 'form-control']) !!}
    </div>
    <div class="form-group {{ $errors->has('price') ? ' has-error' : '' }}">
        <label for="exampleInputEmail1">Цена:</label>
        {{ Form::text('price',isset($product) ? $product->price : null,
                                    [
                                        'id' => 'price',
                                        'class' => 'form-control',
                                        'onkeypress' => 'javascript:return isNumber(event)',
                                        'placeholder' => 'Цена',
                                        'required' => true
                                    ])
        }}
    </div>
</div>

<div class="box-footer">
    {!! Form::submit('Сохранить', ['class' => 'btn btn-primary']) !!}
    <a href="{!! route('products.index') !!}" class="btn btn-default">Отменить</a>
</div>

@section('script')
    <script>
        function isNumber(evt) {
            var iKeyCode = (evt.which) ? evt.which : evt.keyCode
            if (iKeyCode != 46 && iKeyCode > 31 && (iKeyCode < 48 || iKeyCode > 57))
                return false;

            return true;
        }
    </script>
@endsection

resources/views/admin/product/index.blade.php
<?php ?>
@extends('admin.layouts.app')

@section('title')
    Продукты
@endsection
@section('content')
    <section class="content-header">
        <h1>
            Продукты
            <a href="{{ route('products.create') }}" class="btn btn-success">
                <i class="fa fa-btn fa-plus"></i>
                &nbsp;Новый продукт
            </a>
        </h1>
    </section>

    <div class="panel panel-default">
        <div class="panel-body">
            <table class="table table-striped table-bordered table-condensed">
                <thead>
                <tr>
                    <th>Порядок</th>
                    <th>Наименование</th>
                    <th>Цена</th>
                    <th>Кол-во</th>
                    <th>Действия</th>
                </tr>
                </thead>
                <tbody>

                @foreach ($products as $key => $product)

                    <tr>
                        <td>
                            <button id="{{ $product->id }}" class="btn btn-primary btn-block editOrder">
                                {{ $product->order }}
                            </button>
                        </td>
                        <td>
                            <span id="productTitle_{{ $product->id }}">
                                {{ $product->title }}
                            </span>
                        </td>
                        <td>{{ number_format($product->price, 0, '', ' ') }} сум</td>
                        <td contenteditable="true"
                            onblur="updateQuantity({{ $product->id }})"
                            id="updateQuantity_{{ $product->id }}">
                            {{ $product->quantity }}
                        </td>
                        <td>
                            <a class="btn btn-primary" href="{{ route('products.edit',$product->id) }}">
                                <i class="fa fa-btn fa-edit"></i> Edit
                            </a>
                            <form action="{{ url('backend/products/'.$product->id) }}" method="POST"
                                  style="display: inline-block">
                                {{ csrf_field() }}
                                {{ method_field('DELETE') }}

                                <button type="submit" id="delete-task-{{ $product->id }}" class="btn btn-danger">
                                    <i class="fa fa-btn fa-trash"></i> Delete
                                </button>
                            </form>
                        </td>
                    </tr>
                @endforeach
                </tbody>
            </table>

            <div id="dataModal" class="modal fade">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal">&times;</button>
                            <h4 class="modal-title" id="modalTitle"></h4>
                        </div>
                        <div class="modal-body">
                            <form action="{{ route('updateOrder') }}" method="POST">
                                <div class="form-group col-md-6">
                                    <label for="exampleInputEmail1">Old order:</label>
                                    <input type="text" class="form-control productInputOldOrder" disabled="true">
                                </div>
                                <div class="form-group col-md-6">
                                    <label for="exampleInputEmail1">New order:</label>
                                    <input type="text" class="form-control" name="newOrder" id="productInputNewOrder" required>
                                </div>
                                <input type="hidden" name="productId" id="productInputId">
                                <input type="hidden" name="oldOrder" id="productInputOldOrder" class="productInputOldOrder">
                                {{ csrf_field() }}
                                {!! Form::submit('Сохранить', ['class' => 'btn btn-primary']) !!}
                            </form>
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </div>
@endsection

@section('script')
    <script src="{{ asset('sweetalert/sweetalert.min.js') }}"></script>

    <script type="text/javascript">
        $(function () {
            $('.editOrder').click(function () {
                var productId = $(this).attr("id");
                var productName = $('#productTitle_' + productId).html();
                var order = $(this).html();
                $('#modalTitle').html(productName);
                $('#dataModal').modal("show");
                $('#productInputId').val(productId);
                $('.productInputOldOrder').val(order);
            });
        });

        function updateQuantity(id) {
            var quantity = $("#updateQuantity_" + id).html();
            var token = document.getElementsByName("_token")[0].value;
            $.ajax({
                type: "POST",
                url: "{{ url('backend/updateQuantity') }}",
                data: {
                    quantity: quantity,
                    id: id,
                    _token: token
                },
                success: function (response) {
                    swal("Success", response, "success");
                    console.log(response);
                }
            });
        }
    </script>
@endsection