routes/web.php
<?php

Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('login', 'Auth\LoginController@login');
Route::post('logout', 'Auth\LoginController@logout')->name('logout');

Route::get('/', 'HomeController@index')->name('home');
Route::get('category/{slug}', 'HomeController@category')->name('category');
Route::post('order', 'HomeController@order')->name('order');
Route::post('accountingStore', 'HomeController@accountingStore')->name('accountingStore');
Route::view('/accountingIndex', 'accountingIndex');

Route::group(['prefix' => 'backend', 'middleware' => ['role:admin']], function () {

    Route::get('/', 'Admin\BackendController@index');
    Route::resource('accounting', 'Admin\AccountingController');
    Route::post('accountingByDay', 'Admin\AccountingController@accountingByDay')->name('accountingByDay');
    Route::resource('users', 'Admin\UserController');
    Route::resource('categories', 'Admin\CategoryController');
    Route::resource('products', 'Admin\ProductController');
    Route::post('updateOrder', 'Admin\ProductController@updateOrder')->name('updateOrder');
    Route::post('updateQuantity', 'Admin\ProductController@updateQuantity');
    //Orders page
    Route::post('ordersList', 'Admin\OrderController@index')->name('ordersList');
    Route::get('ordersView', 'Admin\OrderController@ordersView')->name('ordersView');
    Route::post('ordersAllList', 'Admin\OrderController@ordersAllList')->name('ordersAllList');
    Route::get('ordersAllView', 'Admin\OrderController@ordersAllView')->name('ordersAllView');

    Route::get('ordersReportView', 'Admin\OrderController@ordersReportView')->name('ordersReportView');
    Route::post('ordersReport', 'Admin\OrderController@ordersReport')->name('ordersReport');

    Route::get('system', 'Admin\SystemController@index')->name('system');
    Route::patch('systemUpdate/{id}', 'Admin\SystemController@update')->name('system.update');

    Route::get('/locationStore','Admin\LocationsController@store');
    Route::get('/locationUpdate','Admin\LocationsController@update');
    Route::get('/locationList','Admin\LocationsController@list');
    Route::view('/locationAdd', 'admin.location.store');
});

app/Http/Controllers/Admin/AccountingController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Model\Accounting;
use App\User;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Yajra\DataTables\Facades\DataTables;

class AccountingController extends Controller
{
    public function index(Request $request)
    {
        if ($request->has('userId') && $request->userId !== null) {
            $users = User::where('id', $request->userId)->paginate(10);
        }else{
            $users = User::orderBy('id')->paginate(10);
        }
        $uersSelect = User::get();
        $usersArray = [];
        foreach ($uersSelect as $item) {
            $usersArray[$item->id] = $item->name;
        }

        return view('admin.accounting.index', compact('users', 'usersArray'));
    }

    public function create(Request $request)
    {
        if ($request->id > 0) {
            $userAccounts = Accounting::where('user_id', '=', $request->id)->orderBy('created_at', 'DESC')->get();

            return DataTables::of($userAccounts)->make(true);
        }
        return null;
    }

    public function store(Request $request)
    {
        $accounting = new Accounting();
        $accounting->user_id = $request->input('user_id');
        $accounting->field_1 = $request->input('field_1');
        $accounting->field_2 = $request->input('field_2');
        $accounting->field_3 = $request->input('field_3');
        $accounting->field_4 = $request->input('field_4');
        $accounting->field_5 = $request->input('field_5');
        $accounting->save();

        return redirect()->route('accounting.show', ['id' => $request->input('user_id')])->with('success', 'Accounting created successfully');
    }

    public function show($id)
    {
        $user = User::find($id);
        return view('admin.accounting.show', compact('user'));
    }

    public function edit($id)
    {
        return view('admin.accounting.accountingByDay');
    }

    public function accountingByDay(Request $request)
    {
        $accounts = Accounting::join('users', 'accounting.user_id', '=', 'users.id')
            ->whereDate('accounting.created_at', '=', $request->orderDate)
            ->orderBy('accounting.balance_at_all', 'DESC')
            ->select(['accounting.*', 'users.name']);

        return DataTables::of($accounts)->make(true);
    }

    public function destroy($id)
    {
        dd($id);
    }
}

app/Http/Controllers/Api/AccountingController.php
<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use App\Model\Accounting;
use App\Model\Order;
use Carbon\Carbon;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Laravel\Passport\Client;

class AccountingController extends Controller
{
    private $client;

    public function __construct()
    {
        $this->client = Client::find(1);
    }

    public function store(Request $request)
    {
        $userId = Auth::user()->id;

        $lastAccounting = Accounting::where('user_id', '=', $userId)->orderBy('created_at', 'desc')->take(1)->first();
        if (empty($lastAccounting))
            $lastBalance = 0;
        else
            $lastBalance = $lastAccounting->balance_at_all;

        $innerSum = $request->input('vnutrenniy');
        $orderSumForToday = $request->input('orderSum');
        $taxSum = $request->input('inkasasiya');
        $terminalSum = $request->input('terminal');
        $balanceSum = $orderSumForToday - $innerSum - $taxSum - $terminalSum;

        $accounting = new Accounting();
        $accounting->user_id = $userId;
        $accounting->orderSumForToday = $orderSumForToday;
        $accounting->innerSum = $innerSum;
        $accounting->taxSum = $taxSum;
        $accounting->terminalSum = $terminalSum;
        $accounting->balanceSum = $balanceSum;
        $accounting->balance_at_all = $lastBalance + $balanceSum;
        $accounting->save();

        return response()->json("", 200);
    }

    public function isAccounting()
    {
        $userId = Auth::user()->id;
        $accounting = Accounting::whereDate('created_at', '=', Carbon::today()->toDateString())->where('user_id', $userId)->first();
        if (empty($accounting))
            return response()->json("", 200);
        else
            return response()->json("", 404);
    }

    public function isOrder()
    {
        $userId = Auth::user()->id;
        $date = Carbon::today()->toDateString();
        $order = Order::whereDate('created_at', '=', $date)->where('user_id', $userId)->first();
        if (empty($order))
            return response()->json('', 404);
        else
            return response()->json($order->total_price, 200);
    }
}

resources/views/admin/accounting/accountingByDay.blade.php
<?php ?>
@extends('admin.layouts.app')

@section('title')
    Бухгалтерия
@endsection

@section('css')
    <link href="{{ asset('DataTables/DataTables-1.10.18/css/jquery.dataTables.min.css') }}" rel="stylesheet">
    <link rel="stylesheet" href="{{ asset('bootstrap-datepicker/css/bootstrap-datepicker.min.css') }}">
    <link rel="stylesheet" href="{{ asset('bootstrap-select/css/bootstrap-select.min.css') }}">
@endsection

@section('content')

    <div class="panel panel-default">
        <div class="panel-body">

            @csrf
            <div class="form-group">
                <div class="input-group">
                    <div class="input-group-addon">
                        <i class="fa fa-calendar"></i>
                    </div>
                    <input type="text" class="form-control" name="dateFilter" id="datepicker"
                           value="{{ old('dateFilter') }}">
                </div>
            </div>

            <table class="table table-striped table-bordered" id="table">
                <thead>
                <tr>
                    <th>Дата</th>
                    <th>Магазин</th>
                    <th>Заказы</th>
                    <th>Внутренний</th>
                    <th>Инкассация</th>
                    <th>Терминал</th>
                    <th>Остаток от заказа</th>
                    <th>Остаток в общем</th>
                </tr>
                </thead>
                <tbody>
                </tbody>
                <tfoot>
                <tr>
                    <th colspan="2" style="text-align:right">Итого:</th>
                    <th></th>
                    <th></th>
                    <th></th>
                    <th></th>
                    <th></th>
                    <th></th>
                </tr>
                </tfoot>
            </table>
        </div>
    </div>
@endsection

@section('script')
    <script src="{{ asset('DataTables/DataTables-1.10.18/js/jquery.dataTables.min.js') }}"></script>
    <script src="{{ asset('DataTables/Buttons-1.5.6/js/dataTables.buttons.min.js') }}"></script>
    <script src="{{ asset('DataTables/Buttons-1.5.6/js/buttons.flash.min.js') }}"></script>
    <script src="{{ asset('DataTables/jszip.min.js') }}"></script>
    <script src="{{ asset('DataTables/moment.min.js') }}"></script>
    <script src="{{ asset('DataTables/pdfmake-0.1.36/pdfmake.min.js') }}"></script>
    <script src="{{ asset('DataTables/pdfmake-0.1.36/vfs_fonts.js') }}"></script>
    <script src="{{ asset('DataTables/Buttons-1.5.6/js/buttons.html5.min.js') }}"></script>
    <script src="{{ asset('DataTables/Buttons-1.5.6/js/buttons.print.min.js') }}"></script>
    <script src="{{ asset('bootstrap-datepicker/js/bootstrap-datepicker.min.js') }}"></script>
    <script src="{{ asset('bootstrap-select/js/bootstrap-select.min.js') }}"></script>

    <script>
        $(function () {

            var _token = $("input[name=_token]").val();
            //Date picker
            $('#datepicker').datepicker({
                autoclose: true,
                format: 'yyyy-mm-dd'
            });

            $('#datepicker').change(function () {
                var orderDate = this.value;
                $("#table").dataTable().fnDestroy();
                $('#table').DataTable({
                    processing: true,
                    serverSide: true,
                    ordering: false,
                    info: false,
                    searching: false,
                    paging: false,
                    ajax: {
                        url: '{!! route( 'accountingByDay' ) !!}',
                        method: "post",
                        data: {orderDate: orderDate, _token: _token},
                    },
                    columns: [
                        {data: 'created_at'},
                        {data: 'name'},
                        {data: 'orderSumForToday'},
                        {data: 'innerSum'},
                        {data: 'taxSum'},
                        {data: 'terminalSum'},
                        {data: 'balanceSum'},
                        {data: 'balance_at_all'}
                    ],
                    columnDefs: [{
                        targets: 0, render: function (data) {
                            return moment(data).format('DD/MM/YYYY');
                        }
                    }],
                    dom: 'Bfrtip',
                    buttons: [
                        {
                            extend: 'print',
                            footer: true
                        },
                        {
                            extend: 'excel',
                            footer: true
                        },
                    ],
                    createdRow: function (row, data, index) {
                        if (data['balance_at_all'] * 1 >= 10000000)
                            $(row).addClass('danger');
                        else if (data['balance_at_all'] * 1 >= 6000000)
                            $(row).addClass('warning');
                        else if (data['balance_at_all'] * 1 >= 3000000)
                            $(row).addClass('success');
                    },
                    "footerCallback": function (row, data, start, end, display) {
                        var api = this.api(), data;

                        // Remove the formatting to get integer data for summation
                        var intVal = function (i) {
                            return typeof i === 'string' ?
                                i.replace(/[\$,]/g, '') * 1 :
                                typeof i === 'number' ?
                                    i : 0;
                        };

                        // Total over this page
                        pageOrdersTotal = api
                            .column(2, {page: 'current'})
                            .data()
                            .reduce(function (a, b) {
                                return intVal(a) + intVal(b);
                            }, 0);
                        pageInnerTotal = api
                            .column(3, {page: 'current'})
                            .data()
                            .reduce(function (a, b) {
                                return intVal(a) + intVal(b);
                            }, 0);
                        pageTaxTotal = api
                            .column(4, {page: 'current'})
                            .data()
                            .reduce(function (a, b) {
                                return intVal(a) + intVal(b);
                            }, 0);
                        pageTerminalTotal = api
                            .column(5, {page: 'current'})
                            .data()
                            .reduce(function (a, b) {
                                return intVal(a) + intVal(b);
                            }, 0);
                        pageCurrentTotal = api
                            .column(6, {page: 'current'})
                            .data()
                            .reduce(function (a, b) {
                                return intVal(a) + intVal(b);
                            }, 0);
                        pageTotal = api
                            .column(7, {page: 'current'})
                            .data()
                            .reduce(function (a, b) {
                                return intVal(a) + intVal(b);
                            }, 0);

                        // Update footer
                        $(api.column(2).footer()).html(pageOrdersTotal);
                        $(api.column(3).footer()).html(pageInnerTotal);
                        $(api.column(4).footer()).html(pageTaxTotal);
                        $(api.column(5).footer()).html(pageTerminalTotal);
                        $(api.column(6).footer()).html(pageCurrentTotal);
                        $(api.column(7).footer()).html(pageTotal);
                    }
                });
            });
        });
    </script>
@endsection

resources/views/admin/accounting/index.blade.php
<?php ?>
@extends('admin.layouts.app')

@section('title')
    Бухгалтерия
@endsection

@section('css')
    <link rel="stylesheet" href="{{ asset('bootstrap-select/css/bootstrap-select.css') }}">
    <script src="{{ asset('bootstrap-select/js/bootstrap-select.js') }}"></script>
@endsection

@section('content')
    <section class="content-header">
        <h1>
            Бухгалтерия
        </h1>
    </section>
    <div class="panel panel-default">
        <div class="panel-body">
            {!! Form::open(['method'=>'GET','url'=>Request::fullUrl(),'role'=>'search', 'autocomplete' => 'off'])  !!}
            <div class="form-group col-md-12">
                <select class="selectpicker form-control"
                        name="userId"
                        data-container="body"
                        data-live-search="true"
                        title="Поиск пользователя"
                        data-hide-disabled="true">
                    @foreach($usersArray as $key=>$index)
                        <option value="{{ $key }}">{{ $index }}</option>
                    @endforeach
                </select>
            </div>

            {!! Form::submit('Фильтровать', ['class' => 'btn btn-primary  btn-block col-md-4']) !!}
            {!! Form::close() !!}


            <table class="table table-striped table-bordered table-condensed">
                <thead>
                <tr>
                    <th>Магазин</th>
                    <th>Остаток</th>
                    <th>Действия</th>
                </tr>
                </thead>
                <tbody>

                @foreach ($users as $user)
<?php
//dd($user->accounting)
?>
                    <tr class="categories-users">
                        <td>{{ $user->name }}</td>
                        <td>{{ $user->username }}</td>
                        <td>
                            <form action="{{ url('backend/accounting/'.$user->id) }}" method="POST"
                                  style="display: inline-block">
                                {{ csrf_field() }}
                                {{ method_field('DELETE') }}

                                <button type="submit" id="delete-task-{{ $user->id }}" class="btn btn-danger">
                                    <i class="fa fa-btn fa-trash"></i> Снять деньгиphp artisan migrate
                                </button>
                            </form>

                            <a href="{{ route('accounting.show', ['id' => $user->id]) }}" type="button"
                               class="btn btn-info">
                                <i class="fa fa-btn fa-calculator"></i> Бухгалтерия
                            </a>
                        </td>
                    </tr>
                @endforeach
                </tbody>
            </table>
        </div>
    </div>
    {{ $users->links() }}
@endsection

@section('script')
    <script src="{{ asset('bootstrap-select/js/bootstrap-select.js') }}"></script>
@endsection

resources/views/admin/accounting/show.blade.php
<?php ?>
@extends('admin.layouts.app')

@section('title')
    {{ $user->name }}
@endsection

@section('css')
    <link href="{{ asset('DataTables/DataTables-1.10.18/css/jquery.dataTables.min.css') }}" rel="stylesheet">
@endsection

@section('content')

    <div class="panel panel-default">
        <div class="panel-body">
            <h3>{{ $user->name }}</h3>

            {{--<button class="btn btn-primary  btn-block" type="button" data-toggle="collapse"--}}
            {{--data-target="#collapseExample"--}}
            {{--aria-expanded="false" aria-controls="collapseExample">--}}
            {{--Добавить за {{ \Carbon\Carbon::now()->format('d/m/Y') }}--}}
            {{--</button>--}}

            {{--<div class="collapse" id="collapseExample">--}}
            {{--<div class="well">--}}
            {{--{!! Form::open(['route' => 'accounting.store']) !!}--}}
            {{--<div class="form-group col-md-4">--}}
            {{--<label for="field_1">Внутренний:</label>--}}
            {{--{{ Form::text('field_1', null, ['min' => '0', 'class' => 'form-control', 'required' => true]) }}--}}
            {{--</div>--}}

            {{--<div class="form-group col-md-4">--}}
            {{--<label for="field_2">Заказы:</label>--}}
            {{--{{ Form::text('field_2', null, ['min' => '0', 'class' => 'form-control', 'required' => true]) }}--}}
            {{--</div>--}}

            {{--<div class="form-group col-md-4">--}}
            {{--<label for="field_3">Инкассация:</label>--}}
            {{--{{ Form::text('field_3', null, ['min' => '0', 'class' => 'form-control', 'required' => true]) }}--}}
            {{--</div>--}}

            {{--<div class="clearfix"></div>--}}

            {{--<div class="form-group col-md-4">--}}
            {{--<label for="field_4">Терминал:</label>--}}
            {{--{{ Form::text('field_4', null, ['min' => '0', 'class' => 'form-control', 'required' => true]) }}--}}
            {{--</div>--}}

            {{--<div class="form-group col-md-4">--}}
            {{--<label for="field_5">Деньги:</label>--}}
            {{--{{ Form::text('field_5', null, ['min' => '0', 'class' => 'form-control', 'required' => true]) }}--}}
            {{--</div>--}}

            {{--<input type="hidden" value="{{ $user->id }}" name="user_id">--}}

            {{--{!! Form::submit('Сохранить', ['class' => 'btn btn-primary  btn-block col-md-4']) !!}--}}
            {{--<div class="clearfix"></div>--}}
            {{--{!! Form::close() !!}--}}
            {{--</div>--}}
            {{--</div>--}}

            <table class="table table-striped table-bordered" id="table">
                <thead>
                <tr>
                    <th>Число</th>
                    <th>Заказы</th>
                    <th>Внутренний</th>
                    <th>Инкассация</th>
                    <th>Терминал</th>
                    <th>Остаток от заказа</th>
                    <th>Остаток в общем</th>
                </tr>
                </thead>
                <tbody>
                </tbody>
            </table>
        </div>
    </div>
@endsection

@section('script')
    <script src="{{ asset('DataTables/DataTables-1.10.18/js/jquery.dataTables.min.js') }}"></script>
    <script src="{{ asset('DataTables/Buttons-1.5.6/js/dataTables.buttons.min.js') }}"></script>
    <script src="{{ asset('DataTables/Buttons-1.5.6/js/buttons.flash.min.js') }}"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.18.1/moment.min.js"></script>
    <script src="{{ asset('DataTables/pdfmake-0.1.36/pdfmake.min.js') }}"></script>
    <script src="{{ asset('DataTables/pdfmake-0.1.36/vfs_fonts.js') }}"></script>
    <script src="{{ asset('DataTables/Buttons-1.5.6/js/buttons.html5.min.js') }}"></script>
    <script src="{{ asset('DataTables/Buttons-1.5.6/js/buttons.print.min.js') }}"></script>

    <script>
        $(function () {
            $('#table').DataTable({
                processing: true,
                serverSide: true,
                ordering: false,
                info: false,
                searching: false,
                paging: true,
                ajax: {
                    url: '{!! route( 'accounting.create', ['id' => $user->id] ) !!}',
                    method: "get",
                },
                columns: [
                    {data: 'created_at'},
                    {data: 'orderSumForToday'},
                    {data: 'innerSum'},
                    {data: 'taxSum'},
                    {data: 'terminalSum'},
                    {data: 'balanceSum'},
                    {data: 'balance_at_all'}
                ],
                columnDefs: [{
                    targets: 0, render: function (data) {
                        return moment(data).format('DD/MM/YYYY');
                    }
                }],
                dom: 'Bfrtip',
                buttons: [
                    'print', 'excel'
                ]
            });
        });
    </script>
@endsection