routes/web.php
<?php

Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('login', 'Auth\LoginController@login');
Route::post('logout', 'Auth\LoginController@logout')->name('logout');

Route::get('/', 'HomeController@index')->name('home');
Route::get('category/{slug}', 'HomeController@category')->name('category');
Route::post('order', 'HomeController@order')->name('order');
Route::post('accountingStore', 'HomeController@accountingStore')->name('accountingStore');
Route::view('/accountingIndex', 'accountingIndex');

Route::group(['prefix' => 'backend', 'middleware' => ['role:admin']], function () {

    Route::get('/', 'Admin\BackendController@index');
    Route::resource('accounting', 'Admin\AccountingController');
    Route::post('accountingByDay', 'Admin\AccountingController@accountingByDay')->name('accountingByDay');
    Route::resource('users', 'Admin\UserController');
    Route::resource('categories', 'Admin\CategoryController');
    Route::resource('products', 'Admin\ProductController');
    Route::post('updateOrder', 'Admin\ProductController@updateOrder')->name('updateOrder');
    Route::post('updateQuantity', 'Admin\ProductController@updateQuantity');
    //Orders page
    Route::post('ordersList', 'Admin\OrderController@index')->name('ordersList');
    Route::get('ordersView', 'Admin\OrderController@ordersView')->name('ordersView');
    Route::post('ordersAllList', 'Admin\OrderController@ordersAllList')->name('ordersAllList');
    Route::get('ordersAllView', 'Admin\OrderController@ordersAllView')->name('ordersAllView');

    Route::get('ordersReportView', 'Admin\OrderController@ordersReportView')->name('ordersReportView');
    Route::post('ordersReport', 'Admin\OrderController@ordersReport')->name('ordersReport');

    Route::get('system', 'Admin\SystemController@index')->name('system');
    Route::patch('systemUpdate/{id}', 'Admin\SystemController@update')->name('system.update');

    Route::get('/locationStore','Admin\LocationsController@store');
    Route::get('/locationUpdate','Admin\LocationsController@update');
    Route::get('/locationList','Admin\LocationsController@list');
    Route::view('/locationAdd', 'admin.location.store');
});

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Laravel\Passport\HasApiTokens;
use Zizaco\Entrust\Traits\EntrustUserTrait;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable, HasApiTokens, EntrustUserTrait;

    protected $fillable = ['name', 'email', 'password', 'username'];

    protected $hidden = ['password', 'remember_token',];

    public static $rules = [
        'name' => ['required', 'string', 'max:255'],
        'username' => ['required', 'string', 'max:255', 'unique:users'],
    ];
    public static $rules_password = ['password' => ['required', 'string', 'min:8', 'confirmed'],];

    public function findForPassport($username)
    {
        return $this->where('username', $username)->first();
    }

    public function accounting()
    {
        return $this->hasMany('App\Model\Accounting');
    }
}

app/Http/Controllers/Admin/UserController.php
<?php

namespace App\Http\Controllers\Admin;

use App\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Hash;
use App\Http\Controllers\Controller;

class UserController extends Controller
{
    public function index(Request $request)
    {
        if ($request->has('userId') && $request->userId !== null) {
            $users = User::where('id', $request->userId)->paginate(10);
        }else{
            $users = User::orderBy('id')->paginate(10);
        }
        $uersSelect = User::get();
        $usersArray = [];
        foreach ($uersSelect as $item) {
            $usersArray[$item->id] = $item->name;
        }

        return view('admin.user.index', compact('users', 'usersArray'));
    }

    public function create()
    {
        return view('admin.user.create');
    }


    public function store(Request $request)
    {
        $this->validate($request, User::$rules);

        $user = new User();
        $user->name = $request->input('name');
        $user->username = $request->input('username');
        $user->password = Hash::make($request->input('password'));
        $user->save();

        return redirect()->route('users.index')->with('success', 'User created successfully');
    }

    public function show($id)
    {
        return redirect()->route('users.index');
    }

    public function edit($id)
    {
        $user = User::find($id);
        return view('admin.user.edit', compact('user'));
    }

    public function update(Request $request, $id)
    {
        $user = User::find($id);

        if ($request->input('name') !== null){
            $user->name = $request->input('name');
            $user->username = $request->input('username');
        }elseif ($request->input('password') !== null){
            $this->validate($request, User::$rules_password);
            $user->password = Hash::make($request->input('password'));
        }else
            return redirect()->route('users.index');

        $user->save();
        return redirect()->route('users.index')->with('success', 'User updated successfully');
    }

    public function destroy($id)
    {
        User::destroy($id);

        return redirect()->route('users.index')->with('success', 'User deleted successfully');
    }
}

resources/views/admin/user/create.blade.php
<?php ?>
@extends('admin.layouts.app')
@section('title')
    Создать пользователь
@endsection
@section('content')
    <section class="content">
        <div class="row">
            <!-- left column -->
            <div class="col-md-12">
                <!-- general form elements -->
                <div class="box box-primary">
                    <div class="box-header with-border">
                        <h3 class="box-title">Создать пользователь</h3>
                    </div>

                    {!! Form::open(['route' => 'users.store']) !!}

                    @include('admin.user.fields')

                    {!! Form::close() !!}

                </div>
            </div>
        </div>
    </section>
@endsection

resources/views/admin/user/edit.blade.php
@extends('admin.layouts.app')
@section('title')
    Редактировать пользователь
@endsection
@section('content')
    <section class="content">
        <div class="row">
            <!-- left column -->
            <div class="col-md-12">
                <!-- general form elements -->
                <div class="box box-primary">
                    <div class="box-header with-border">
                        <h3 class="box-title">Редактировать пользователь</h3>
                    </div>

                    {!! Form::model($user, ['route' => ['users.update', $user->id], 'method' => 'patch']) !!}

                    @include('admin.user.fields')

                    {!! Form::close() !!}

                </div>
            </div>
        </div>
    </section>
@endsection

resources/views/admin/user/fields.blade.php
@if (count($errors) > 0)
    <div class="alert alert-danger alert-dismissible">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        <h4><i class="icon fa fa-ban"></i> Alert!</h4>
        @foreach ($errors->all() as $error)
            <p>{{ $error }}</p>
        @endforeach
    </div>
@endif

<div class="box-body">
    <div class="form-group @error('name') has-error @enderror">
        <label for="name" class="col-md-4 col-form-label text-md-right">Наименование</label>

        <input id="name" type="text" class="form-control @error('name') is-invalid @enderror" name="name"
               value="{{ isset($user) ? $user->name : old('name') }}" required autocomplete="name" autofocus>

        @error('name')
        <span class="invalid-feedback" role="alert">
            <strong>{{ $message }}</strong>
        </span>
        @enderror
    </div>

    <div class="form-group @error('username') has-error @enderror">
        <label for="username" class="col-md-4 col-form-label text-md-right">Логин</label>

        <input id="username" type="text" class="form-control @error('username') is-invalid @enderror"
               name="username"
               value="{{ isset($user) ? $user->username : old('username') }}" required autocomplete="username">

        @error('username')
        <span class="invalid-feedback" role="alert">
            <strong>{{ $message }}</strong>
        </span>
        @enderror
    </div>

    <div class="form-group @error('password') has-error @enderror">
        <label for="password" class="col-md-4 col-form-label text-md-right">Пароль</label>

        <input id="password" type="password" class="form-control @error('password') is-invalid @enderror"
               name="password" required autocomplete="new-password">

        @error('password')
        <span class="invalid-feedback" role="alert">
            <strong>{{ $message }}</strong>
        </span>
        @enderror
    </div>

    <div class="form-group">
        <label for="password-confirm" class="col-md-4 col-form-label text-md-right">Повторить пароль</label>

        <input id="password-confirm" type="password" class="form-control" name="password_confirmation" required
                   autocomplete="new-password">
    </div>

</div>

<div class="box-footer">
    {!! Form::submit('Сохранить', ['class' => 'btn btn-primary']) !!}
    <a href="{!! route('products.index') !!}" class="btn btn-default">Отменить</a>
</div>

resources/views/admin/user/index.blade.php
<?php ?>
@extends('admin.layouts.app')

@section('title')
    Пользователи
@endsection

@section('css')
    <link rel="stylesheet" href="{{ asset('bootstrap-select/css/bootstrap-select.css') }}">
    <script src="{{ asset('bootstrap-select/js/bootstrap-select.js') }}"></script>
@endsection

@section('content')
    <section class="content-header">
        <h1>
            Пользователи
            <a href="{{ route('users.create') }}" class="btn btn-success">
                <i class="fa fa-btn fa-plus"></i>
                &nbsp;Новый пользователь
            </a>
        </h1>
    </section>
    <div class="panel panel-default">
        <div class="panel-body">
            {!! Form::open(['method'=>'GET','url'=>Request::fullUrl(),'role'=>'search', 'autocomplete' => 'off'])  !!}
                <div class="form-group col-md-12">
                    <select class="selectpicker form-control"
                            name="userId"
                            data-container="body"
                            data-live-search="true"
                            title="Поиск пользователя"
                            data-hide-disabled="true">
                        @foreach($usersArray as $key=>$index)
                            <option value="{{ $key }}">{{ $index }}</option>
                        @endforeach
                    </select>
                </div>

                {!! Form::submit('Фильтровать', ['class' => 'btn btn-primary  btn-block col-md-4']) !!}
            {!! Form::close() !!}


            <table class="table table-striped table-bordered table-condensed">
                <thead>
                <tr>
                    <th>Наименование</th>
                    <th>Логин</th>
                    <th>Действия</th>
                </tr>
                </thead>
                <tbody>

                @foreach ($users as $user)

                    <tr class="categories-users">
                        <td>{{ $user->name }}</td>
                        <td>{{ $user->username }}</td>
                        <td>
                            {{--<a class="btn btn-primary" href="{{ route('users.edit',$user->id) }}">--}}
                            {{--<i class="fa fa-btn fa-edit"></i> Edit--}}
                            {{--</a>--}}
                            <button type="button" class="btn btn-primary" data-toggle="modal"
                                    data-target="#userEditModal_{{ $user->id }}">
                                <i class="fa fa-btn fa-edit"></i> Edit
                            </button>
                            <!-- Modal -->
                            <div class="modal fade" id="userEditModal_{{ $user->id }}" tabindex="-1" role="dialog"
                                 aria-labelledby="myModalLabel">
                                <div class="modal-dialog" role="document">
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                <span aria-hidden="true">&times;</span></button>
                                            <h4 class="modal-title" id="myModalLabel">{{ $user->name }}</h4>
                                        </div>
                                        {!! Form::model($user, ['route' => ['users.update', $user->id], 'method' => 'patch']) !!}
                                        <div class="modal-body">


                                            <div class="form-group @error('name') has-error @enderror">
                                                <label for="name" class="col-md-4 col-form-label text-md-right">Наименование</label>

                                                <input id="name" type="text"
                                                       class="form-control"
                                                       name="name"
                                                       value="{{ $user->name }}"
                                                       autocomplete="name">
                                                @error('name')
                                                <span class="invalid-feedback" role="alert">
                                                        <strong>{{ $message }}</strong>
                                                    </span>
                                                @enderror
                                            </div>

                                            <div class="form-group @error('username') has-error @enderror">
                                                <label for="username" class="col-md-4 col-form-label text-md-right">Логин</label>

                                                <input id="username" type="text"
                                                       class="form-control"
                                                       name="username"
                                                       value="{{ $user->username }}"
                                                       required autocomplete="username">
                                                @error('username')
                                                <span class="invalid-feedback" role="alert">
                                                        <strong>{{ $message }}</strong>
                                                    </span>
                                                @enderror
                                            </div>


                                        </div>
                                        <div class="modal-footer">
                                            <button type="button" class="btn btn-default" data-dismiss="modal">Close
                                            </button>
                                            {!! Form::submit('Сохранить', ['class' => 'btn btn-primary']) !!}
                                        </div>
                                        {!! Form::close() !!}
                                    </div>
                                </div>
                            </div>

                            <form action="{{ url('backend/users/'.$user->id) }}" method="POST"
                                  style="display: inline-block">
                                {{ csrf_field() }}
                                {{ method_field('DELETE') }}

                                <button type="submit" id="delete-task-{{ $user->id }}" class="btn btn-danger">
                                    <i class="fa fa-btn fa-trash"></i> Delete
                                </button>
                            </form>

                            <button type="button" class="btn btn-warning" data-toggle="modal"
                                    data-target="#userPasswordChange_{{ $user->id }}">
                                <i class="fa fa-btn fa-lock"></i> Change password
                            </button>
                            <!-- Modal -->
                            <div class="modal fade" id="userPasswordChange_{{ $user->id }}" tabindex="-1" role="dialog"
                                 aria-labelledby="myModalLabel">
                                <div class="modal-dialog" role="document">
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                                <span aria-hidden="true">&times;</span></button>
                                            <h4 class="modal-title" id="myModalLabel">{{ $user->name }}</h4>
                                        </div>
                                        {!! Form::model($user, ['route' => ['users.update', $user->id], 'method' => 'patch']) !!}
                                        <div class="modal-body">
                                            <div class="form-group @error('password') has-error @enderror">
                                                <label for="password" class="col-md-4 col-form-label text-md-right">Пароль</label>

                                                <input id="password" type="password"
                                                       class="form-control @error('password') is-invalid @enderror"
                                                       name="password" required autocomplete="new-password">

                                                @error('password')
                                                <span class="invalid-feedback" role="alert">
                                                        <strong>{{ $message }}</strong>
                                                    </span>
                                                @enderror
                                            </div>

                                            <div class="form-group">
                                                <label for="password-confirm"
                                                       class="col-md-4 col-form-label text-md-right">Повторить
                                                    пароль</label>

                                                <input id="password-confirm" type="password" class="form-control"
                                                       name="password_confirmation" required
                                                       autocomplete="new-password">
                                            </div>
                                        </div>
                                        <div class="modal-footer">
                                            <button type="button" class="btn btn-default" data-dismiss="modal">Close
                                            </button>
                                            {!! Form::submit('Сохранить', ['class' => 'btn btn-primary']) !!}
                                        </div>
                                        {!! Form::close() !!}
                                    </div>
                                </div>
                            </div>

                            <a href="{{ route('accounting.show', ['id' => $user->id]) }}" type="button"
                               class="btn btn-info">
                                <i class="fa fa-btn fa-calculator"></i> Бухгалтерия
                            </a>
                        </td>
                    </tr>
                @endforeach
                </tbody>
            </table>
        </div>
    </div>
    {{ $users->links() }}
@endsection

@section('script')
    <script src="{{ asset('bootstrap-select/js/bootstrap-select.js') }}"></script>
@endsection